- name: Install dependencies
  apt:
    name:
      - 'zsh'
    state: latest
  tags: ['zsh']

- name: Change default shell to zsh for user
  user:
    name: "{{ dev_user }}"
    shell: /bin/zsh
  tags: ['zsh']

- name: Ensure .zshrc file exists
  file:
    path: "/root/.zshrc"
    state: touch
  tags: ['zsh']

- name: Ensure .profile is sourced in .zshrc
  lineinfile:
    path: "/root/.zshrc"
    line: "source ~/.profile"
    insertbefore: BOF
    state: present
  tags: ['zsh']

- name: Copy .zshrc to user home directory with proper ownership
  copy:
    src: "/root/.zshrc"
    dest: "/home/{{ dev_user }}/.zshrc"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
  tags: ['zsh']
